spring.application.name=veterinaria
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?user=postgres.pxcastrqbfxicqctqsym&password=[YOUR-PASSWORD]
spring.datasource.username=postgres.pxcastrqbfxicqctqsym
spring.datasource.password=Jc3102054428
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect